version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    container_name: jenkins
    volumes:
      - ~/jenkins/jenkins-data:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: /home/jenkins/jenkins/ubuntu-folder
    networks:
      - net
networks:
  net:
