FROM rockylinux/rockylinux

MAINTAINER devopsdjengo@gmail.com 
RUN yum install -y httpd \
	zip \
	unzip

ADD https://www.free-css.com/assets/files/free-css-templates/download/page287/cycle.zip /var/www/html

WORKDIR /var/www/html

RUN unzip cycle.zip

RUN CP -rvf cycle/* .

RUN rm -rf cycle.zip cycle 

CMD ["/usr/bin/httpd", "-D", "FOREGROUND"]

EXPOSE 80

